version: '3.8'

services:
  web:
    build: ./web
    ports:
      - "8080:80"
    volumes:
      - ./web:/var/www/html
    depends_on:
      - db
    links:
      - db
    networks:
      - backend

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: chatbot
      MYSQL_USER: chatbot_user
      MYSQL_PASSWORD: chatbot_pw
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - backend


  ai:
    build: ./ai
    ports:
      - "5000:5000"
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: chatbot_project-phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpw
    networks:
      - backend

networks:
  backend:

volumes:
  chatbot_db_data:
